apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
# Specification mentioning the replicas and the selector which will be used for service.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app

# Specification for containers where the image from docker hub is being used
# Alongside the resources that are needed to run the application
    spec:
      containers:
        - name: flask-app-container
          image: mvnsib/finalflaskapp
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
              ephemeral-storage: "5Gi"
          ports:
            - containerPort: 5000
              protocol: TCP